name: Daily Post

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate daily post
      run: |
        mkdir -p _posts
        POST_DATE=$(date +"%Y-%m-%d")
        POST_FILE="_posts/$POST_DATE-daily-post.md"
        echo "---" > $POST_FILE
        echo "layout: post" >> $POST_FILE
        echo "title: \"Daily Post for $POST_DATE\"" >> $POST_FILE
        echo "date: $POST_DATE" >> $POST_FILE
        echo "categories: daily" >> $POST_FILE
        echo "---" >> $POST_FILE
        echo "This is the daily post for $POST_DATE." >> $POST_FILE

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add _posts/
        git commit -m "Add daily post for $(date +\"%Y-%m-%d\")"
        git push
